name: my_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9  # You can specify your preferred Python version
  - matplotlib=3.9.2
  - numpy=2.1.3
  - pytorch=2.5.1
  - torchvision=0.20.1
  - tqdm=4.67.0